apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragment
spec:
  template:
    spec:
      containers:
        - name: php
          volumeMounts:
            - mountPath: /opt/app-root/src/platform/public/build/netlify
              name: content
        - name: nginx
          volumeMounts:
            - mountPath: /opt/app-root/src/platform/public/build/netlify
              name: content
              readOnly: true
      volumes:
        - name: content
          emptyDir: {}
        - name: scripts
          configMap:
            defaultMode: 420
            name: fragment-init-content-script
