version: '3.0'
services:
  design-system-fragment-nginx:
    image: jfrog-mt1.gamesys.co.uk/enjoy-base-docker-release-local/redhat-nginx:1.18
    ports:
      - "8085:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-node.conf:/etc/nginx/nginx-node.conf
      - ./nginx/worker_parameters.conf:/etc/nginx/worker_parameters.conf
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled
      - ./nginx/fragment-sites-enabled/:/etc/nginx/fragment-sites-enabled
      - ../platform:/opt/app-root/src/platform
    extra_hosts:
      - "host.docker.internal:host-gateway"

