kind: CronJob
apiVersion: batch/v1
metadata:
  name: task
spec:
  jobTemplate:
    metadata:
    spec:
      template:
        spec:
          containers:
            - name: task
              image: example-4-app-cron-1
