apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-assets
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - example-2-app-assets
                topologyKey: kubernetes.io/hostname
