apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-assets
spec:
  replicas: 2
  template:
    spec:
      volumes:
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: example-2-app
            readOnly: true
