apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: design-system-fragment

resources:
  - ../shared-configs/fragment/base-nginx

patchesStrategicMerge:
  - patch-deployment-images.yaml
  - patch-deployment-readiness.yaml
  - patch-deployment-resources.yaml
