apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - resources:
          # these are the default that we are usually applying to stg and prod
            limits:
              cpu: 450m
              memory: 2G
            requests:
              cpu: 250m
              memory: 1G
          name: java
