apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../java-app/base
  - ../../../cron/base

components:
  - ../../../java-app/components/nginx-assets

commonLabels:
  app: example-2-app

patchesStrategicMerge:
  - patch-deployment-images.yaml
  - patch-cron-images.yaml
