apiVersion: skaffold/v2beta9
kind: Config

metadata:
  name: design-system-fragment

build:
  artifacts:
    - image: design-system-frontend
      context: ./platform
      docker:
        dockerfile: Dockerfile-frontend


# To be able to run the local version of the software you will have to
# configure docker to talk to the minikube registry instead of the remote.
# This can be done by running eval $(minikube docker-env) before running skaffold.
deploy:
  kubeContext: docker-for-desktop
  kustomize:
    paths:
      - kustomize/base

profiles:
  - name: qa-mt1            # Stub profile, for backwards compatibility
  - name: qa-release-stg    # Stub profile, for backwards compatibility
  - name: rdge-eph
    deploy:
      kustomize:
        paths:
          - kustomize/overlays/rdge-eph
  - name: afun-eph
    deploy:
      kustomize:
        paths:
          - kustomize/overlays/afun-eph
  - name: plng-eph
    deploy:
      kustomize:
        paths:
          - kustomize/overlays/plng-eph

  - name: baso-eph
    deploy:
      kustomize:
        paths:
        - kustomize/overlays/baso-eph
