apiVersion: apps/v1  # API version
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis:5.0.8
          env:
            - name: REDIS_PASSWORD
              value: abcdefgh
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: 100m
              memory: 100M
          ports:
            - containerPort: 6379
              name: redis
