---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: example-2-

resources:
  - ../../base
  - resources/ingress.yaml
  - resources/sealed-secrets.yaml

commonLabels:
  gamesys.com/deployable: example-2-app

patchesStrategicMerge:
  - patches/app/patch-deployment-additional.yaml
  - patches/app/patch-deployment-affinity.yaml
  - patches/app/patch-deployment-configmap.yaml
  - patches/app/patch-deployment-env-vars.yaml
  - patches/app/patch-deployment-resources.yaml
  - patches/app/patch-deployment-readiness.yaml
  - patches/cronjob/patch-cronjob-configmap.yaml
  - patches/cronjob/patch-cronjob-env-vars.yaml
  - patches/cronjob/patch-cronjob-resources.yaml
  - patches/cronjob/patch-cronjob-schedule.yaml
  - patches/nginx-assets/patch-nginx-deployment-additional.yaml
  - patches/nginx-assets/patch-nginx-deployment-affinity.yaml
  - patches/nginx-assets/patch-nginx-deployment-env-vars.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/labels/isMonitored
      value: monitored
  target:
    kind: Service
    version: v1
    name: app-svc

configMapGenerator:
  - name: app-config
    files:
       - configmaps/application-stg-k8s.yaml

namespace: plng-stg-backend
