kind: CronJob
apiVersion: batch/v1
metadata:
  name: task
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - resources:
                limits:
                  cpu: 1
                  memory: 2G
                requests:
                  cpu: 300m
                  memory: 1G
              name: task
