apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      gamesys.com/component: app
  replicas: 1
  template:
    metadata:
      labels:
        gamesys.com/component: app
    spec:
      containers:
      - name: java
        env:
        - name: TZ
          value: UTC
        image: PATCH_ME
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 512M
            cpu: 10m
          limits:
            memory: 1G
      automountServiceAccountToken: false
      dnsConfig:
        options:
          - name: edns0
