apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    gamesys.com/servicemonitor: springboot
spec:
  ports:
    - name: java-app
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    gamesys.com/component: app
