apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-content
spec:
  template:
    spec:
      containers:
        - name: nginx-content
          volumeMounts:
            - mountPath: /mnt/shared
              name: content
              readOnly: true
      volumes:
        - name: content
          emptyDir: {}
        - name: scripts
          configMap:
            defaultMode: 420
            name: nginx-init-content-script
