apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: nginx-conf
    files:
      - config/nginx.conf
      - config/nginx-node.conf
      - config/worker_parameters.conf
  - name: nginx-sites-enabled
    files:
      - config/sites-enabled/8080_server-status.conf
