apiVersion: v1
kind: Service
metadata:
  name: fragment-svc
spec:
  ports:
    - name: nginx
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: status
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: fragment
