apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragment
spec:
  template:
    spec:
      containers:
      - resources:
          limits:
            memory: 500M
          requests:
            cpu: 100m
            memory: 250M
        name: nginx
