apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: example-5-app

resources:
  - ../../../java-app/base

patchesStrategicMerge:
  - patch-deployment-images.yaml

components:
  - ../../../java-app/components/nginx-content
  - ../../../java-app/components/_init-container-script
  - ../../../java-app/components/content-init-container

configMapGenerator:
  - name: nginx-init-content-config
    literals:
      - ARTEFACT_NAME=example-artefact
      - FOLDER_NAME=translations
      - CONTENT_REPO=example/example-content
      - CONTENT_REPO_BRANCH=master
