apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragment
spec:
  template:
    spec:
      initContainers:
        - name: init-images-content
          image: registry-mt1.enjoy-platform.net/base-images/alpine:3.10.3
          command:
            - sh
            - /scripts/content-deploy.sh
          env:
            - name: VOLUME_DIR
              value: images
            - name: CONFIG_MAP_NAME
              value: fragment-init-images-config
            - name: SECRET_NAME
              value: git-private-token
          envFrom:
            - configMapRef:
                name: fragment-init-images-config
            - secretRef:
                name: git-private-token
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: images
              mountPath: /images
          resources:
            limits:
              cpu: 200m
              memory: 400M
            requests:
              cpu: 50m
              memory: 50M
