apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: plng-stg-backend
spec:
  encryptedData:
    secret1: xyz
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example-2-app
      name: example-2-app-secrets
      namespace: plng-stg-backend
    type: Opaque

