apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragment
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      dnsConfig:
        options:
          - name: edns0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: php
        env:
        - name: APP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        - name: APP_DEBUG
          value: "0"
        - name: JWT_PASSPHRASE
          valueFrom:
            secretKeyRef:
              key: passphrase
              name: fragments-jwt-certs
        - name: JWT_PRIVATE_KEY_PATH
          value: config/jwt/private.pem
        - name: JWT_PUBLIC_KEY_PATH
          value: config/jwt/public.pem
        - name: TZ
          value: UTC
        image: PATCH_ME
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 3
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 3
        resources:
          limits:
            memory: 400M
          requests:
            cpu: 10m
            memory: 200M
        volumeMounts:
        - mountPath: /opt/app-root/src/platform/config/jwt
          name: jwt-certs-volume
        - mountPath: /opt/app-root/src/platform/var
          name: var-emptydir
        - mountPath: /etc/php-fpm.d/www.conf
          name: php-fpmd
          subPath: www.conf
        - mountPath: /etc/php-fpm.conf
          name: php-conf
          subPath: php-fpm.conf
        - mountPath: /etc/php.ini
          name: php-conf
          subPath: php.ini
      - name: nginx
        env:
        - name: APP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        - name: TZ
          value: UTC
        image: PATCH_ME
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /nginx_status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /nginx_status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 200M
          requests:
            cpu: 10m
            memory: 50M
        volumeMounts:
        - mountPath: /etc/nginx/sites-enabled
          name: nginx-sites-enabled
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /etc/nginx/php.conf
          name: nginx-conf
          subPath: php.conf
        - mountPath: /etc/nginx/worker_parameters.conf
          name: nginx-conf
          subPath: worker_parameters.conf
        - mountPath: /var/log/nginx
          name: var-log-nginx-emptydir
        - mountPath: /var/cache/nginx
          name: var-cache-nginx-emptydir
      volumes:
        - name: jwt-certs-volume
          secret:
            secretName: fragments-jwt-certs
        - emptyDir: {}
          name: var-emptydir
        - emptyDir: {}
          name: var-cache-nginx-emptydir
        - emptyDir: {}
          name: var-log-nginx-emptydir
        - configMap:
            name: fragment-php-fpmd
          name: php-fpmd
        - configMap:
            name: fragment-php-conf
          name: php-conf
        - configMap:
            name: fragment-nginx-sites-enabled
          name: nginx-sites-enabled
        - configMap:
            name: fragment-nginx-conf
          name: nginx-conf
