apiVersion: v1
kind: Service
metadata:
  name: fragment-svc
  labels:
    gamesys.com/servicemonitor: php
spec:
  ports:
    - name: nginx-status
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: php-app
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: fragment
